### ISSUE TITLE
i am a poet. where to install and how to launch ml4a?

### ISSUE THREAD

**Issue by ucy74** [ml4a/ml4a-ofx#14]
i would like to play with convnetClassifier.
ml4a must be dropped inside OF folder or maybe standalone?
how to launch?

**Comment by AndreasRef** [comment]
Hi @ucy74 

If you just want to play with convnetClassifier and do not have any experience with openFrameworks you might want to have a look at [ml4a-ofx releases](https://github.com/ml4a/ml4a-ofx/releases/tag/v0.1) which is a collection of standalone executables. 

Do however note that convnetClassifer is Mac only.
Best Andreas

**Comment by ucy74** [comment]
Thanks for releases!
But once again pls,
where should I drop ml4a source files?
I work on Mac with xcode

**Comment by AndreasRef** [comment]
Have you tried compiling openFrameworks projects before? If not, check out this guide: http://openframeworks.cc/setup/xcode/

**Comment by genekogan** [comment]
you can drop ml4a source files wherever you want, and then generate the Xcode projects with openframeworks project generator. as @AndreasRef mentioned, please review http://openframeworks.cc/setup/xcode/

**Comment by HerrBertling** [comment]
I ran into this as well – it's not that intuitive for people not used to XCode, the project setup etc. I managed to get everything up and running after reading this and tinkering with it. Coming from a HTML/CSS and bits of JS background, this was okay-ish to do. I can imagine people not that familiar with tooling setups to struggle quite a lot with setting up any ml4a project.

I'd like to prepare a PR with some basic documentation on how to setup a project and get it running – and thus answer the questions posed in this issue's topic. Would that be okay?

**Comment by genekogan** [comment]
@HerrBertling, yes this would be tremendously useful. It could potentially fit into the [guides](https://ml4a.github.io/guides/) as well. Unfortunately our documentation for things like this is still lacking, but we are planning a big push on that front and so it would be very helpful.
