### ISSUE TITLE
Error when compiling AudioClassifier app using VisualStudio

### ISSUE THREAD

**Issue by Pems** [ml4a/ml4a-ofx#21]
Hello. So, I downloaded the latest version of openFrameworks as well as the ml4a-ofx repository, and used the Project Generator to create a Visual Studio solution for the AudioClassifier app. Next I got the addons that the app uses, and placed them in the addons folder. At first I was getting some errors with the GRT addon, but I realized that the ofxGrt repo didn't have the GRT folder that appears [here](https://github.com/nickgillian/grt), so I placed the folder inside the addon's folder and it solved the issue.

However, with the ofxMaxim addon I get another issue: I noticed the [github repo](https://github.com/falcon4ever/ofxMaxim) links to [another repo](https://github.com/micknoise/Maximilian/tree/master/openFrameworks) which contains the same addon, but updated more recently. I have tried copying both folders into the addons folder, but I get different results with each. I attach screenshots. I have tried merging the contents of both folders into one, but I still get errors.

This is from the falcon4ever repo:
![falcon4ever_ofxmaxim](https://user-images.githubusercontent.com/6728331/32533119-c60a3a62-c41c-11e7-93b3-15689923ee4d.png)

And this is from the Maximilian repo:
![micknoise_maximilian](https://user-images.githubusercontent.com/6728331/32533074-75dac624-c41c-11e7-8dfc-190c1db29803.png)

I haven't tried the other apps yet, but any help with this would be very appreciated.

**Comment by genekogan** [comment]
can you get any of the examples working with ofxMaxim? this appears to be an issue with ofxMaxim, not the ml4a-ofx examples.

**Comment by Pems** [comment]
Hi. Well, kinda... I managed to make the ofMaximExampleVS2010 run, but it doesn't recognize the keyboard input. I got some errors at first, but they were due to being made in an erlier version of Visual Studio and openFrameworks. 

Now, when I try to compile again the AudioClassifier app I get only this error: "Error	LNK2001	unresolved external symbol "public: __thiscall GRT::FFT::FFT(unsigned int,unsigned int,unsigned int,unsigned int,bool,bool)" (??0FFT@GRT@@QAE@IIII_N0@Z)	AudioClassifier	D:\Open Frameworks\ml4a-ofx-master\apps\AudioClassifier\FFTFeatures.obj". I really have no idea what to make out of this, especially because when I browse the folder there's no FFTFeatures.obj file, which I'm asuming is part of the build process from Visual Studio... but beyond that I have no idea what could it be.

Do you have testimonies of people making it work on windows so far?

**Comment by genekogan** [comment]
it seems perhaps you didn't download the GRT libs with the submodule. see the instructions in the ofxGRT github page.


    cd ofxGRT
    git submodule init
    git submodule update
