### ISSUE TITLE
ConvNet Classifier

### ISSUE THREAD

**Issue by geekkid1** [ml4a/ml4a-ofx#24]
I use a windows 10 laptop but I still want to use convnetClassifier. Is there any way to do that? I know the most recently released executable (there should be more, IMO. If it seems appropriate, I would suggest releasing compiled again soon) only has Mac-Compatible, but compiling it from source on my computer is a pain. Does anybody have any ideas/advice?

**Comment by genekogan** [comment]
ConvnetClassifier won't build in windows because we have not successfully built [libccv](http://libccv.org//) for windows. if you are able to, a PR would be most welcome.
