### ISSUE TITLE
tSNE-images.py float32 not serializable by json.dumps

### ISSUE THREAD

**Issue by cameronbergh** [ml4a/ml4a-ofx#27]
json dumps wont serialize float32's.
looks like this has been an issue for years idk wtf.

changing line 76 to this

        point = [np.float64((tsne[i, k] - np.min(tsne[:, k])) / (np.max(tsne[:, k]) - np.min(tsne[:, k]))) for k in
                 range(tsne_dimensions)]

seems to fix the problem... at least for the imageTsneViewer program because i cant get imageTsneLive to compile

ubuntu 17.10, python3

**Comment by genekogan** [comment]
this should be fixed as of today. please let me know if it's still not working for you.
