### ISSUE TITLE
Convnet Predictor Issue - Virtual Function Clear has different definition than function it overrides

### ISSUE THREAD

**Issue by heaversm** [ml4a/ml4a-ofx#32]
Error building convnet predictor:

```
/src/PipelineThreaded.h:19:18: Virtual function 'clear' has a different return type ('void') than the function it overrides (which has return type 'bool')
```

ofx 10.0 on OSX 10.13.6 (XCode)

**Comment by genekogan** [comment]
this should be fixed now. let me know if it doesn't compile still.

**Comment by amozeng** [comment]
Hi I was trying to run the FacePredictor app, and just got the same error:

PipelineThreaded.h:19:18: Virtual function 'clear' has a different return type ('void') than the function it overrides (which has return type 'bool')

Thanks!

**Comment by amozeng** [comment]
This can get fixed by changing the method type from void to bool, and return bool in each function. Just like the update in "ConvnetPredictor" app
