### ISSUE TITLE
I cannot find your "Bohemian Rhapsody demo".

### ISSUE THREAD

**Issue by bemoregt** [ml4a/ml4a-ofx#33]
Hi, @lassse @dotKokott @frnsys @genekogan @HerrBertling 

I cannot find your "Bohemian Rhapsody demo".

Is that removed in the Youtube?

Please give me a link.

Thanks.

from @bemoregt.

**Comment by genekogan** [comment]
this demo is the result of running the audio t-SNE script in the scripts folder on an audio file. the example we used is bohemian rhapsody but the actual demo is not packaged with the repository. you would have to run it yourself on an mp3 of your choice. hope that is useful.

**Comment by bemoregt** [comment]
OK, I got it.
